from django.urls import path
from . import views

app_name = 'events'

urlpatterns = [
    path('events/', views.event_list, name='event_list'),
    # path('events/<str:title>/', views.event_detail, name='event-detail'),
    path('event/create/', views.create_event, name='create_event'),
    path('events/<int:event_id>/', views.event_detail, name='event_detail'),
    path('events/schedules/create/', views.create_schedule, name='create_schedule'),
    path('schedules/', views.schedule_list, name='schedule-list'),
    path('speakers/create/', views.create_speaker, name='create_speaker'),
    path('categories/', views.category_list, name='category_list'),
    path('speakers/', views.speaker_list, name='speaker_list'),
    path('speakers/<str:name>/', views.speaker_detail, name='speaker_detail'),
    path('participants/', views.participant_list, name='participant_list'),
    path('participants/<str:email>/', views.participant_detail, name='participant_detail'),
    path('payments/', views.payment_list, name='payment_list'),
    path('payments/participant/<str:email>/',views.payment_by_participant, name='payment-by-participant'),
    path('participants/create/', views.create_participant, name='create_participant'),
    path('payments/create/', views.create_payment, name='create_payment'),
    path('upcoming/', views.upcoming_events, name='upcoming_events'),
    path('free-events/', views.free_events, name='free-events'),
    path('paid-events/',views.paid_events, name='paid-events'),
    # path('participant-count-per-event/',views.participant_count_per_event, name='participant-count-per-event'),
    # path('event-count-per-participant/', views.event_count_per_participant, name='event-count-per-participant'),
    # path('schedule-count-per-event/', views.schedule_count_per_event, name='schedule-count-per-event'),
    #  path('total-amount-paid-for-event/<str:title>/', views.total_amount_paid_for_event, name='total-amount-paid-for-event'),
#     path('average-price-of-paid-events/', views.average_price_of_paid_events, name='average-price-of-paid-events'),
#     path('participants-attending-event/<str:title>/',views.participants_attending_event, name='participants-attending-event'),
#     path('speakers-for-event/<str:title>/', views.speakers_for_event, name='speakers-for-event'),
#     path('events-in-date-range/', views.events_in_date_range, name='events-in-date-range'),
   path('participants-attended-all-events/', views.participants_attended_all_events, name='participants-attended-all-events'),
#     path('events-without-speakers/', views.events_without_speakers, name='events-without-speakers'),
#     path('events-highest-amount-paid/', views.events_highest_amount_paid, name='events-highest-amount-paid'),
#     path('participants-highest-payment/', views.participants_highest_payment, name='participants-highest-payment'),
#     path('speakers-most-scheduled-events/', views.speakers_most_scheduled_events, name='speakers-most-scheduled-events'),
#     path('events-longest-duration/', views.events_longest_duration, name='events-longest-duration'),
#     path('participants-most-events-in-month/', views.participants_most_events_in_month, name='participants-most-events-in-month'),
#     path('events-with-overlapping-schedules/', views.events_with_overlapping_schedules, name='events-with-overlapping-schedules'),
#     path('participants-recent-payment/', views.participants_recent_payment, name='participants-recent-payment'),
#     path('participants-attended-consecutive-events/',views.participants_attended_consecutive_events, name='participants-attended-consecutive-events'),
#     path('speakers-no-assigned-events/', views.speakers_no_assigned_events, name='speakers-no-assigned-events'),
#     path('events-highest-total-payment/', views.events_highest_total_payment, name='events-highest-total-payment'),
#     path('participants-attended-multiple-locations/', views.participants_attended_multiple_locations, name='participants-attended-multiple-locations'),
#     path('speakers-different-topics/', views.speakers_different_topics, name='speakers-different-topics'),
#     path('events-longest-gap-between-dates/', views.events_longest_gap_between_dates, name='events-longest-gap-between-dates'),
#     path('participants-attended-location-events/', views.participants_attended_location_events, name='participants-attended-location-events'),
#     path('speakers-highest-average-rating/', views.speakers_highest_average_rating, name='speakers-highest-average-rating'),
#     path('participants-paid-for-all-events/', views.participants_paid_for_all_events, name='participants-paid-for-all-events'),
]
